Fix go version and move send to SendAsync
streamnative/pulsar-beat-output pull request #18
Opened 2019-11-02 02:51 UTC by tuteng

* Update native-go-client to latest
* Move sync send to async send
* Add config DisableBatching and BatchingMaxPublishDelay

2019-11-02 13:48 UTC, sijie requested changes

2019-11-02 13:48 UTC, sijie commented on pulsar/config.go
> -	Batching                           bool                      `config:"batching"`
this is a breaking change. Can we keep this and mark it as deprecated?

2019-11-02 13:48 UTC, sijie commented on pulsar/config.go
> +	BatchingMaxPublishDelay            int             `config:"batching_max_publish_delay"`
This is a breaking change. Do we really need to change the type?

2019-11-02 13:48 UTC, sijie commented on vendor/github.com/apache/pulsar-client-go/examples/consumer-listener/consumer-listener.go
> +	"fmt"
It seems that there are many format changes. Can we do the format changes in a separate pull request?

2019-12-20 06:48 UTC, sijie commented
need a pulsar-client-go release.

2020-04-25 00:59 UTC, tuteng commented
Close this pr, it has been fixed #20

2020-04-25 00:59 UTC, closed without merging